ALTER TABLE users
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS institution VARCHAR(200),
    ADD COLUMN IF NOT EXISTS orcid VARCHAR(50),
    ADD COLUMN IF NOT EXISTS degree VARCHAR(100),
    ADD COLUMN IF NOT EXISTS education_summary TEXT,
    ADD COLUMN IF NOT EXISTS years_experience INT,
    ADD COLUMN IF NOT EXISTS cv_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS profile_picture VARCHAR(500),
    ADD COLUMN IF NOT EXISTS publications_list TEXT,
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
    ADD COLUMN IF NOT EXISTS organization VARCHAR(200),
    ADD COLUMN IF NOT EXISTS areas_of_interest TEXT,
    ADD COLUMN IF NOT EXISTS investment_range VARCHAR(100);

CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
