ALTER TABLE users
    ADD COLUMN IF NOT EXISTS position VARCHAR(120),
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE research
    ADD COLUMN IF NOT EXISTS collaborators TEXT,
    ADD COLUMN IF NOT EXISTS comment_count INT NOT NULL DEFAULT 0;
