export * as authApi from './auth';
export * as researchApi from './research';
export * as collaborationApi from './collaboration';
export * as chatApi from './chat';
export * as notificationsApi from './notifications';
export * as aiApi from './ai';
export * as adminApi from './admin';
export * as fundingApi from './funding';
export { getToken, setToken, clearToken, BASE_URL } from './client';
export { default as apiClient } from './client';
