spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/researchiq
    username: postgres
    password: researchiq_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    validate-on-migrate: false
    clean-disabled: true
    url: jdbc:postgresql://localhost:5432/researchiq
    user: postgres
    password: researchiq_password
  mail:
    host: smtp.gmail.com
    port: 587
    username: ineshirwa8@gmail.com
    password: gchgzrudqxylzinc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

logging:
  level:
    root: INFO
    com.umojatech.researchiq: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/app.log

app:
  security:
    jwt:
      secretKey: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
      expirationMs: 3600000
      refreshExpirationMs: 86400000
      issuer: "researchiq-dev"
  bootstrap-admin:
    email: ineshirwa8@gmail.com
    password: "79544921"
    name: System Admin
